### ISSUE TITLE
2.3.4 compile error Class Magento\Framework\Search\EngineResolverInterface does not exist

### ISSUE THREAD

**Issue by scottbolasevich** [swissup/swissup.github.io#18]
I just upgraded to 2.3.4 and my installation will not compile now due to 

html/vendor/swissup/module-ajaxsearch/Model/Layer/Search/ItemCollectionProvider.php

use Magento\Framework\Search\EngineResolverInterface;

Is there a fix?

Exception trace:
 () at /chroot/home/a7406982/xxx/html/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29
 ReflectionParameter->getClass() at /chroot/home/a7406982/xxx/html/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29
 Magento\Framework\Code\Reader\ClassReader->getConstructor() at /chroot/home/a7406982/xxx/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassReaderDecorator.php:35
 Magento\Setup\Module\Di\Code\Reader\ClassReaderDecorator->getConstructor() at /chroot/home/a7406982/xxx/html/setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Area.php:53
 Magento\Setup\Module\Di\Code\Reader\Decorator\Area->getList() at /chroot/home/a7406982/xxx/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php:109
 Magento\Setup\Module\Di\App\Task\Operation\Area->getDefinitionsCollection() at /chroot/home/a7406982/dev.spikesfeed.com/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php:84
 Magento\Setup\Module\Di\App\Task\Operation\Area->doOperation() at /chroot/home/a7406982/dev.spikesfeed.com/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
 Magento\Setup\Module\Di\App\Task\Manager->process() at /chroot/home/a7406982/xxx/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:205
 Magento\Setup\Console\Command\DiCompileCommand->execute() at /chroot/home/a7406982/xxx/html/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at /chroot/home/a7406982/xxx/html/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at /chroot/home/a7406982/xxx/html/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /chroot/home/a7406982/xxx/html/lib/internal/Magento/Framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /chroot/home/a7406982/xxx/html/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /chroot/home/a7406982/xxx/html/bin/magento:23

**Comment by scottbolasevich** [comment]
nevermind this appears to be caused because my lib/internal/Magento/Framework/* is out of date

**Comment by 0m3r** [comment]
I have a patch for backward compatibility with 2.2 

~~~diff
diff --git a/Model/Layer/Search/ItemCollectionProvider.php b/Model/Layer/Search/ItemCollectionProvider.php
index 71fc6ee..38c3f65 100644
--- a/Model/Layer/Search/ItemCollectionProvider.php
+++ b/Model/Layer/Search/ItemCollectionProvider.php
@@ -3,7 +3,6 @@
 namespace Swissup\Ajaxsearch\Model\Layer\Search;
 
 use Magento\Catalog\Model\Layer\ItemCollectionProviderInterface;
-use Magento\Framework\Search\EngineResolverInterface;
 
 /**
  * Catalog search category layer collection provider.
@@ -12,9 +11,9 @@
 class ItemCollectionProvider implements ItemCollectionProviderInterface
 {
     /**
-     * @var EngineResolverInterface
+     * @var \Swissup\Ajaxsearch\Search\EngineResolverInterfaceFactory
      */
-    private $engineResolver;
+    private $engineResolverInterfaceFactory;
 
     /**
      * @var array
@@ -23,14 +22,14 @@ class ItemCollectionProvider implements ItemCollectionProviderInterface
 
     /**
      * ItemCollectionProvider constructor.
-     * @param EngineResolverInterface $engineResolver
+     * @param \Swissup\Ajaxsearch\Search\EngineResolverInterfaceFactory $engineResolver
      * @param array $factories
      */
     public function __construct(
-        EngineResolverInterface $engineResolver,
+        \Swissup\Ajaxsearch\Search\EngineResolverInterfaceFactory $engineResolverInterfaceFactory,
         array $factories
     ) {
-        $this->engineResolver = $engineResolver;
+        $this->engineResolverInterfaceFactory = $engineResolverInterfaceFactory;
         $this->factories = $factories;
     }
 
@@ -39,10 +38,16 @@ public function __construct(
      */
     public function getCollection(\Magento\Catalog\Model\Category $category)
     {
-        if (!isset($this->factories[$this->engineResolver->getCurrentSearchEngine()])) {
-            throw new \DomainException('Undefined factory ' . $this->engineResolver->getCurrentSearchEngine());
+        $currentSearchEngine = 'mysql';
+        if ($this->engineResolverInterfaceFactory->isExist()) {
+            $currentSearchEngine = $this->engineResolverInterfaceFactory->create()
+                ->getCurrentSearchEngine();
         }
-        $collection = $this->factories[$this->engineResolver->getCurrentSearchEngine()]->create();
+
+        if (!isset($this->factories[$currentSearchEngine])) {
+            throw new \DomainException('Undefined factory ' . $currentSearchEngine);
+        }
+        $collection = $this->factories[$currentSearchEngine]->create();
 
         return $collection;
     }
diff --git a/Search/EngineResolverInterfaceFactory.php b/Search/EngineResolverInterfaceFactory.php
new file mode 100644
index 0000000..4ccc9e4
--- /dev/null
+++ b/Search/EngineResolverInterfaceFactory.php
@@ -0,0 +1,48 @@
+<?php
+
+namespace Swissup\Ajaxsearch\Search;
+
+use Magento\Framework\ObjectManagerInterface;
+
+class EngineResolverInterfaceFactory
+{
+    /**
+     * Entity class name
+     */
+    const CLASS_NAME = \Magento\Framework\Search\EngineResolverInterface::class;
+
+    /**
+     * Object Manager instance
+     *
+     * @var ObjectManagerInterface
+     */
+    protected $objectManager = null;
+
+    /**
+     * Factory constructor
+     *
+     * @param ObjectManagerInterface $objectManager
+     */
+    public function __construct(ObjectManagerInterface $objectManager)
+    {
+        $this->objectManager = $objectManager;
+    }
+
+    /**
+     *
+     * @return bool
+     */
+    public function isExist()
+    {
+        return interface_exists(self::CLASS_NAME) || interface_exists(self::CLASS_NAME, false);
+    }
+
+    /**
+     *
+     * @return \Magento\Framework\Search\EngineResolverInterface
+     */
+    public function create()
+    {
+        return $this->objectManager->create(self::CLASS_NAME);
+    }
+}
~~~
