### ISSUE TITLE
Swissup_ThemeEditor doesn't exist?

### ISSUE THREAD

**Issue by radiumsoup** [swissup/swissup.github.io#7]
Following install instructions for Absolute theme on Magento 2.0.1, and I cannot find the Swissup_ThemeEditor module anywhere. I also had to go find the Swissup_core module elsewhere on my own, the instructions did not send me there or let me know where to start looking. I gave up after 90 minutes of looking for Swissup_ThemeEditor

**Comment by roma84** [comment]
You can skip enabling Swissup_ThemeEditor. It will be available in the next version only.
